CC = gcc
# FILES = quadraticFormula.o:quadraticFormula.c citardarqFormula.o:citardarqFormula.c
CFLAGS = -std=c11 -Wall -pedantic -c
LDFLAGS = -lm

build:
	$(CC) -c quadraticFormula.c
	$(CC) -c citardarqFormula.c



# quadraticFormula.o: quadraticFormula.c
#
# citardarqFormula.o: citardarqFormula.c

clean:
	-rm quadraticFormula.o
	-rm citardarqFormula.o
